In [33]:
import pandas as pd
import numpy as np

In [34]:
df=pd.read_csv('IRIS.csv')

In [35]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [36]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [37]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [42]:
print(y_test)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2]


In [43]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [47]:
print(x_test)

[[-0.04622511  2.3720024  -1.48043619 -1.31466572]
 [-0.89033581 -1.240184   -0.4597716  -0.15276803]
 [ 0.91847283 -0.03612186  0.33407864  0.2345312 ]
 [-0.52857408  2.13118998 -1.4237326  -1.05646624]
 [ 2.48610699  1.89037755  1.46815041  1.00912966]
 [ 0.5567111   0.68631542  0.50418941  0.49273069]
 [ 1.28023456  0.20469056  0.73100376  1.39642889]
 [-0.89033581  1.89037755 -1.08351107 -1.05646624]
 [-1.37268478  0.44550299 -1.25362184 -1.31466572]
 [ 1.28023456  0.44550299  1.07122529  1.39642889]
 [-0.2873996  -0.75855914  0.22067147  0.10543146]
 [-0.52857408  2.13118998 -1.19691825 -1.05646624]
 [ 1.52140905 -0.03612186  1.18463247  1.13822941]
 [ 0.67729835  0.44550299  0.39078223  0.36363094]
 [ 0.19494938 -0.27693429  0.39078223  0.36363094]
 [-1.73444651  0.44550299 -1.4237326  -1.31466572]
 [-0.04622511 -0.99937157  0.10726429 -0.02366829]
 [-0.2873996  -0.03612186  0.39078223  0.36363094]
 [-0.52857408  0.92712784 -1.31032543 -1.05646624]
 [-1.01092305  0.44550299 -1.48

In [46]:
print(x_train)

[[ 0.31553662 -0.03612186  0.44748582  0.2345312 ]
 [ 2.2449325  -0.03612186  1.29803965  1.39642889]
 [-0.2873996  -1.240184    0.0505607  -0.15276803]
 [ 0.67729835 -0.51774672  1.01452171  1.13822941]
 [-0.04622511 -0.51774672  0.73100376  1.52552864]
 [-0.64916132  1.64956512 -1.31032543 -1.31466572]
 [-0.40798684 -1.72180885  0.10726429  0.10543146]
 [-0.76974857  0.92712784 -1.36702901 -1.31466572]
 [ 0.79788559 -0.51774672  0.44748582  0.36363094]
 [ 1.03906007 -1.240184    1.12792888  0.75093018]
 [ 1.15964732 -0.03612186  0.95781812  1.13822941]
 [-0.89033581  1.16794027 -1.36702901 -1.18556598]
 [ 0.19494938 -1.96262128  0.67430017  0.36363094]
 [ 0.5567111  -0.27693429  1.01452171  0.75093018]
 [ 0.91847283 -0.27693429  0.44748582  0.10543146]
 [ 2.2449325  -0.99937157  1.75166836  1.39642889]
 [-0.16681235  1.89037755 -1.19691825 -1.18556598]
 [-1.01092305  1.4087527  -1.36702901 -1.31466572]
 [-1.25209754 -0.03612186 -1.36702901 -1.18556598]
 [-0.76974857 -0.75855914  0.05

In [49]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [50]:
model.predict(x_test)

array([-0.30206823,  0.86890543,  1.16199732, -0.08604872,  1.8464844 ,
        1.42667729,  1.77220961,  0.17515719,  0.05739721,  1.97118316,
        1.25805038,  0.04591586,  1.89391418,  1.28906937,  1.37170362,
        0.02270952,  1.09901388,  1.45844461, -0.02519986, -0.1388531 ,
        1.29526419,  1.50130177,  1.48602672, -0.05361152,  1.76001901,
        1.20465735, -0.16974683, -0.00597775,  1.26771953,  1.66494833])

In [52]:
print(model.score(x_test,y_test)*100)

88.45578423495648
